/**
 * Markdown content negotiation for www.pgupai.com.
 *
 * Serves the Markdown twin of a page when a client negotiates
 * `text/markdown`, per https://acceptmarkdown.com — same URL, correct
 * `Content-Type`, `Vary: Accept`, real q-value parsing, and `406` when the
 * client accepts nothing we can produce.
 *
 * Design notes:
 *  - Everything is wrapped in try/catch and falls through to normal static
 *    serving on any error. A bug here must never take the site down.
 *  - HTML requests return `undefined` (continue the chain) so Vercel serves
 *    the static file exactly as before. `Vary: Accept` is attached to those
 *    responses by the `headers` rules in vercel.json, not here.
 *  - The route table is generated by scripts/build-markdown.mjs; a stale
 *    table degrades to "no Markdown for that page", never to a broken page.
 */
import { negotiate } from './lib/negotiate.mjs';
import { ROUTES, NOT_FOUND_MARKDOWN } from './lib/routes.mjs';

/**
 * Paths the middleware never touches: static assets, the Markdown twins
 * themselves (fetching one must not re-enter this function), machine-readable
 * files served as-is, and the /x social-share shim.
 */
export const config = {
  matcher: ['/((?!assets/|md/|_vercel/|x$|.*\\.[a-zA-Z0-9]+$).*)'],
};

/** Representations this site can serve, best first. HTML stays the default. */
const PRODUCES = ['text/html', 'text/markdown'];

const MARKDOWN_TYPE = 'text/markdown; charset=utf-8';

/** Normalise a request path to the clean URL used as the route-table key. */
export function canonicalPath(pathname) {
  let out = pathname.replace(/\/{2,}/g, '/');
  if (out.length > 1) out = out.replace(/\/+$/, '');
  out = out.replace(/\.html$/, '');
  if (out === '/index') return '/';
  if (out.endsWith('/index')) out = out.slice(0, -'/index'.length);
  return out || '/';
}

/** Look up the Markdown twin for a clean URL, or null when there isn't one. */
export function markdownTwinFor(pathname) {
  return ROUTES[canonicalPath(pathname)] ?? null;
}

/**
 * RFC 9110 recommends a 406 body that lists what the resource can produce.
 * @param {string} accept the Accept header we could not satisfy
 */
function notAcceptable(accept) {
  const body =
    'This resource is available in:\n' +
    '- text/html\n' +
    '- text/markdown\n\n' +
    `You requested: ${accept}\n`;
  return new Response(body, {
    status: 406,
    headers: {
      'content-type': 'text/plain; charset=utf-8',
      // Cache-busting: the same URL answers 200 for a different Accept.
      'cache-control': 'no-store',
      vary: 'Accept, Accept-Encoding',
    },
  });
}

/** Markdown body for a path that does not exist, with routes back into the site. */
function notFoundMarkdown(pathname, origin) {
  return (
    '# 404 — Page not found\n\n' +
    `No page exists at \`${pathname}\` on this site.\n\n` +
    '## Where to look next\n\n' +
    `- [Home](${origin}/) — what J-Bot Review is and how to install it\n` +
    `- [Guides](${origin}/guides) — every provider and setup path\n` +
    `- [llms.txt](${origin}/llms.txt) — the machine-readable fact sheet, including when to use this project\n` +
    `- [sitemap.xml](${origin}/sitemap.xml) — every canonical URL on this site\n` +
    `- [Action repository](https://github.com/pgup-ai/jbot-review-action) — inputs, providers, and configuration\n\n` +
    'Every page here also serves Markdown to `Accept: text/markdown`.\n'
  );
}

/**
 * Extract Vercel's deployment-protection cookie, if present.
 *
 * The subrequest below is same-origin to our own deployment. On a protected
 * preview it would otherwise be intercepted by the SSO wall, so forward just
 * that one cookie — never the caller's whole Cookie header.
 */
function protectionCookie(request) {
  const cookie = request.headers.get('cookie');
  if (!cookie) return null;
  const match = /(?:^|;\s*)(_vercel_jwt=[^;]+)/.exec(cookie);
  return match ? match[1] : null;
}

/**
 * True when a subrequest returned something that is not our Markdown twin.
 *
 * A deployment-protection interstitial, an error page, or a CDN notice all
 * answer 200 with HTML. Serving one of those under a text/markdown
 * Content-Type would hand an agent a page of markup and claim it was
 * Markdown, which is worse than not negotiating at all.
 */
function isNotMarkdown(response, body) {
  const type = response.headers.get('content-type') || '';
  if (/\bhtml\b/i.test(type)) return true;
  return /^\s*<(?:!|html|head|body)/i.test(body);
}

export default async function middleware(request) {
  try {
    const method = request.method.toUpperCase();
    if (method !== 'GET' && method !== 'HEAD') return undefined;

    const url = new URL(request.url);
    const accept = request.headers.get('accept');
    const chosen = negotiate(accept, PRODUCES);

    // Nothing we can produce is acceptable to this client.
    if (chosen === null) return notAcceptable(accept ?? '');

    // HTML is the default path: let the static file serve untouched.
    if (chosen !== 'text/markdown') return undefined;

    const twin = markdownTwinFor(url.pathname);
    if (!twin) {
      // Unknown path. Answer 404 in the format the agent asked for so it can
      // recover, rather than handing it the styled HTML error page.
      return new Response(notFoundMarkdown(canonicalPath(url.pathname), url.origin), {
        status: 404,
        headers: {
          'content-type': MARKDOWN_TYPE,
          'cache-control': 'public, max-age=0, must-revalidate',
          vary: 'Accept, Accept-Encoding',
        },
      });
    }

    // Vercel strips Content-Type from any middleware-produced response to a
    // HEAD request — and Content-Type is exactly what acceptmarkdown.com's
    // `curl -sI` compliance check reads. Rewriting to the static twin instead
    // lets the file-serving layer set the headers, which it keeps on HEAD.
    // `Vary` still comes from the vercel.json rule for the requested path.
    if (method === 'HEAD') {
      return new Response(null, {
        headers: { 'x-middleware-rewrite': new URL(twin, url.origin).toString() },
      });
    }

    const cookie = protectionCookie(request);
    const upstream = await fetch(new URL(twin, url.origin), {
      headers: cookie ? { cookie } : undefined,
    });
    // If the twin is missing or something answered in its place, fall back to
    // the HTML page rather than serving the wrong bytes as Markdown.
    if (!upstream.ok) return undefined;

    const markdown = await upstream.text();
    if (isNotMarkdown(upstream, markdown)) return undefined;

    return new Response(markdown, {
      status: 200,
      headers: {
        'content-type': MARKDOWN_TYPE,
        'cache-control': 'public, max-age=0, must-revalidate',
        vary: 'Accept, Accept-Encoding',
        // Point agents back at the HTML representation of the same resource.
        link: `<${url.origin}${canonicalPath(url.pathname)}>; rel="canonical"`,
        'x-content-type-options': 'nosniff',
      },
    });
  } catch {
    // Fail open: any unexpected error serves the site exactly as before.
    return undefined;
  }
}
