// GENERATED by scripts/build-markdown.mjs — do not edit by hand.
// Maps every clean URL to the Markdown twin the middleware serves for it.

export const ROUTES = Object.freeze({
  '/': '/md/index.md',
  '/about': '/md/about.md',
  '/compare/coderabbit-alternative': '/md/compare/coderabbit-alternative.md',
  '/compare/cubic-alternative': '/md/compare/cubic-alternative.md',
  '/compare/greptile-alternative': '/md/compare/greptile-alternative.md',
  '/compare/qodo-alternative': '/md/compare/qodo-alternative.md',
  '/contact': '/md/contact.md',
  '/guides': '/md/guides/index.md',
  '/guides/claude-code-review-github-actions': '/md/guides/claude-code-review-github-actions.md',
  '/guides/cli-subscription-code-review': '/md/guides/cli-subscription-code-review.md',
  '/guides/cline-code-review-github-actions': '/md/guides/cline-code-review-github-actions.md',
  '/guides/codex-code-review-github-actions': '/md/guides/codex-code-review-github-actions.md',
  '/guides/command-code-review-github-actions': '/md/guides/command-code-review-github-actions.md',
  '/guides/cursor-code-review-github-actions': '/md/guides/cursor-code-review-github-actions.md',
  '/guides/deepseek-v4-flash-code-review-github-actions': '/md/guides/deepseek-v4-flash-code-review-github-actions.md',
  '/guides/devin-code-review-github-actions': '/md/guides/devin-code-review-github-actions.md',
  '/guides/grok-code-review-github-actions': '/md/guides/grok-code-review-github-actions.md',
  '/guides/kilo-code-review-github-actions': '/md/guides/kilo-code-review-github-actions.md',
  '/guides/kimi-code-review-github-actions': '/md/guides/kimi-code-review-github-actions.md',
  '/guides/ling-3-0-flash-code-review-github-actions': '/md/guides/ling-3-0-flash-code-review-github-actions.md',
  '/guides/local-agent-code-review': '/md/guides/local-agent-code-review.md',
  '/guides/muse-spark-code-review-github-actions': '/md/guides/muse-spark-code-review-github-actions.md',
  '/guides/openai-compatible-code-review-github-actions': '/md/guides/openai-compatible-code-review-github-actions.md',
  '/guides/poolside-code-review-github-actions': '/md/guides/poolside-code-review-github-actions.md',
  '/privacy': '/md/privacy.md',
});

/** Body served when an agent negotiates Markdown for a path that does not exist. */
export const NOT_FOUND_MARKDOWN = '/md/404.md';
